# Generated by Django 6.0.3 on 2026-03-14 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='User',
            new_name='user',
        ),
    ]
