# Generated by Django 6.0.3 on 2026-03-17 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0003_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='created',
            new_name='created_at',
        ),
    ]
