# Generated by Django 6.0.3 on 2026-03-18 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0004_rename_created_otp_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='created_at',
            new_name='created',
        ),
    ]
